/*
 * Hibernate Search, full-text search for your domain model
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
package org.hibernate.search.elasticsearch.impl;

import java.util.Map;

import org.hibernate.search.elasticsearch.impl.mapping.TypeMapping;

/**
 * An object responsible for validating type mappings retrieved from an existing Elasticsearch instance
 * against Hibernate Search-generated type mappings.
 *
 * @author Yoann Rodiere
 */
public interface ElasticsearchMappingsValidator {

	/**
	 * Validate a set of type mappings, throwing an exception if validation fails.
	 *
	 * @param expectedTypeMapping The expected mapping, generated by Hibernate Search.
	 * @param actualTypeMapping The actual mapping, retrieved from Elasticsearch.
	 * @throws ElasticsearchMappingValidationException If a validation error occurs.
	 */
	void validate(Map<String, TypeMapping> expectedTypeMapping, Map<String, TypeMapping> actualMapping);

}
